#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
config_dir="${HOME}/.config/youtube-summary"
config_file="${config_dir}/config.env"
bin_dir="${HOME}/.local/bin"
link_path="${bin_dir}/youtube-summary"
project_root_quoted="$(printf "%q" "$project_root")"

missing=0
for tool in python3 codex; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "[ERROR] Missing dependency: $tool" >&2
    missing=1
  fi
done

if ! python3 -c 'import youtube_transcript_api' >/dev/null 2>&1; then
  echo "[ERROR] Missing Python dependency: youtube-transcript-api" >&2
  echo "        Install it with: python3 -m pip install youtube-transcript-api" >&2
  missing=1
fi

if ! command -v yt-dlp >/dev/null 2>&1; then
  echo "[WARN] yt-dlp not found; metadata will fall back to the video ID." >&2
fi

if [[ "$missing" -ne 0 ]]; then
  echo "Install missing dependencies, then run install.sh again." >&2
  exit 127
fi

mkdir -p "$config_dir" "$bin_dir"

if [[ ! -e "$config_file" ]]; then
  cp "$project_root/config/config.example.env" "$config_file"
  echo "Created config: $config_file"
else
  echo "Config already exists, left unchanged: $config_file"
fi

chmod +x \
  "$project_root/bin/youtube-summary" \
  "$project_root/providers/"*.sh \
  "$project_root/scripts/"*.sh \
  "$project_root/scripts/"*.py

if [[ -e "$link_path" && ! -L "$link_path" ]]; then
  if ! grep -q "Generated by youtube-summary install.sh" "$link_path" 2>/dev/null; then
    echo "[ERROR] Refusing to overwrite non-youtube-summary file: $link_path" >&2
    exit 1
  fi
fi

cat > "$link_path" <<EOF
#!/usr/bin/env bash
# Generated by youtube-summary install.sh
set -euo pipefail

project_root=$project_root_quoted

if [[ -x "\$project_root/.venv/bin/python" ]]; then
  export PATH="\$project_root/.venv/bin:\$PATH"
  exec "\$project_root/.venv/bin/python" "\$project_root/bin/youtube-summary" "\$@"
fi

exec python3 "\$project_root/bin/youtube-summary" "\$@"
EOF

chmod +x "$link_path"

cat <<EOF
Installed youtube-summary:
  $link_path

Next steps:
  1. Ensure $bin_dir is in PATH.
  2. Edit $config_file if needed.
  3. Run:
     youtube-summary "https://youtu.be/dQw4w9WgXcQ" --verbose

Hammerspoon:
  Add this to ~/.hammerspoon/init.lua:
     dofile("$project_root/hammerspoon/youtube-summary.lua")
EOF
