#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
config_dir="${HOME}/.config/tubefold"
config_file="${config_dir}/config.env"
bin_dir="${HOME}/.local/bin"
link_path="${bin_dir}/tubefold"

missing=0
if ! command -v swift >/dev/null 2>&1; then
  echo "[ERROR] Missing dependency: swift (install Xcode or the Command Line Tools)" >&2
  missing=1
fi

# A provider CLI is needed at runtime. Either Codex or Claude Code works; both use
# the user's own subscription (no API key). Require at least one.
have_codex=0
have_claude=0
command -v codex >/dev/null 2>&1 && have_codex=1
command -v claude >/dev/null 2>&1 && have_claude=1
if [[ "$have_codex" -eq 0 && "$have_claude" -eq 0 ]]; then
  echo "[ERROR] Missing provider CLI: install 'codex' or 'claude' (Claude Code)." >&2
  missing=1
else
  [[ "$have_codex" -eq 0 ]] && echo "[WARN] codex not found; provider=codex will be unavailable." >&2
  [[ "$have_claude" -eq 0 ]] && echo "[WARN] claude not found; provider=claude will be unavailable." >&2
fi

if [[ "$missing" -ne 0 ]]; then
  echo "Install missing dependencies, then run install.sh again." >&2
  exit 127
fi

echo "Building the tubefold CLI (release)…"
swift build -c release --package-path "$project_root/TubeFoldKit" --product tubefold

mkdir -p "$config_dir" "$bin_dir"

if [[ ! -e "$config_file" ]]; then
  cp "$project_root/config/config.example.env" "$config_file"
  echo "Created config: $config_file"
else
  echo "Config already exists, left unchanged: $config_file"
fi

# Symlink the built binary. Bundle resources (the prompt template) resolve next
# to the real binary, so the symlink target must stay inside the build dir.
built_binary="$project_root/TubeFoldKit/.build/release/tubefold"
[[ -x "$built_binary" ]] || { echo "[ERROR] Build produced no binary at $built_binary" >&2; exit 1; }
if [[ -e "$link_path" && ! -L "$link_path" ]]; then
  if ! grep -q "Generated by tubefold install.sh" "$link_path" 2>/dev/null; then
    echo "[ERROR] Refusing to overwrite non-tubefold file: $link_path" >&2
    exit 1
  fi
fi
ln -sf "$built_binary" "$link_path"

# Older installs also linked a tubefold-server launcher; the local API lives
# inside the macOS app, so drop a stale launcher if we own it.
server_link_path="${bin_dir}/tubefold-server"
if [[ -f "$server_link_path" ]] && grep -q "Generated by tubefold install.sh" "$server_link_path" 2>/dev/null; then
  rm "$server_link_path"
  echo "Removed obsolete launcher: $server_link_path"
fi

cat <<EOF
Installed tubefold:
  $link_path -> $built_binary

Next steps:
  1. Ensure $bin_dir is in PATH.
  2. Edit $config_file if needed.
  3. Run:
     tubefold "https://youtu.be/dQw4w9WgXcQ" --verbose

Chrome Extension:
  The extension talks to the TubeFold macOS app (it serves the local API on
  127.0.0.1:43821 while running). Install it from the Chrome Web Store:
     https://chromewebstore.google.com/detail/tubefold-mac-app-companio/hjfcdpioihmgoccmfkcicofjgbkjidbh
     (source: https://github.com/TubeFold/extension)
EOF
