#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
link_path="${HOME}/.local/bin/tubefold"
server_link_path="${HOME}/.local/bin/tubefold-server"

if [[ -L "$link_path" && "$(readlink "$link_path")" == "$project_root/TubeFoldKit/.build/release/tubefold" ]]; then
  rm "$link_path"
  echo "Removed symlink: $link_path"
elif [[ -L "$link_path" && "$(readlink "$link_path")" == "$project_root/bin/tubefold" ]]; then
  rm "$link_path"
  echo "Removed legacy symlink: $link_path"
elif [[ -f "$link_path" ]] && grep -q "Generated by tubefold install.sh" "$link_path" 2>/dev/null; then
  rm "$link_path"
  echo "Removed launcher: $link_path"
else
  echo "No tubefold launcher owned by this checkout was found at: $link_path"
fi

# Launcher left behind by older installs.
if [[ -f "$server_link_path" ]] && grep -q "Generated by tubefold install.sh" "$server_link_path" 2>/dev/null; then
  rm "$server_link_path"
  echo "Removed launcher: $server_link_path"
fi

if [[ "${1:-}" == "--remove-config" ]]; then
  rm -f "${HOME}/.config/tubefold/config.env"
  echo "Removed config: ${HOME}/.config/tubefold/config.env"
else
  echo "User config left unchanged. Pass --remove-config to delete it."
fi
