#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
link_path="${HOME}/.local/bin/youtube-summary"
server_link_path="${HOME}/.local/bin/youtube-brain-server"

if [[ -L "$link_path" && "$(readlink "$link_path")" == "$project_root/bin/youtube-summary" ]]; then
  rm "$link_path"
  echo "Removed symlink: $link_path"
elif [[ -f "$link_path" ]] && grep -q "Generated by youtube-summary install.sh" "$link_path" 2>/dev/null; then
  rm "$link_path"
  echo "Removed launcher: $link_path"
else
  echo "No youtube-summary launcher owned by this checkout was found at: $link_path"
fi

if [[ -f "$server_link_path" ]] && grep -q "Generated by youtube-summary install.sh" "$server_link_path" 2>/dev/null; then
  rm "$server_link_path"
  echo "Removed launcher: $server_link_path"
fi

if [[ "${1:-}" == "--remove-config" ]]; then
  rm -f "${HOME}/.config/youtube-summary/config.env"
  echo "Removed config: ${HOME}/.config/youtube-summary/config.env"
else
  echo "User config left unchanged. Pass --remove-config to delete it."
fi
