import Foundation

/// YAML front-matter generation, provider-output post-processing, prompt
/// templating and the ".md" credit footer.
///
/// Key invariant: the YAML front matter is generated by the pipeline, never by
/// the model; providers produce only the Markdown body.
public enum SummaryText {
    public static let projectName = "TubeFold"
    public static let projectURL = "https://tubefold.github.io/"

    /// Scalar value in the generated YAML front matter.
    public enum YAMLScalar: Equatable, Sendable {
        case null
        case bool(Bool)
        case int(Int)
        case string(String)

        var rendered: String {
            switch self {
            case .null: "\"\""
            case let .bool(value): value ? "true" : "false"
            case let .int(value): String(value)
            case let .string(value): jsonEncodedString(value)
            }
        }
    }

    /// Render ordered `key: value` pairs as a front-matter block, ending with
    /// a blank line. The exact rendering is part of the saved-file format.
    public static func yamlFrontMatter(_ fields: [(String, YAMLScalar)]) -> String {
        var lines = ["---"]
        for (key, value) in fields {
            lines.append("\(key): \(value.rendered)")
        }
        lines.append("---")
        return lines.joined(separator: "\n") + "\n\n"
    }

    /// Combined model field, e.g. `codex gpt-5.4-mini (effort: medium)`.
    public static func modelLabel(provider: String, model: String, reasoningEffort: String = "") -> String {
        let provider = provider.trimmingCharacters(in: .whitespacesAndNewlines)
        let model = model.trimmingCharacters(in: .whitespacesAndNewlines)
        let effort = reasoningEffort.trimmingCharacters(in: .whitespacesAndNewlines)
        var label = model.isEmpty ? provider : "\(provider) \(model)".trimmingCharacters(in: .whitespaces)
        // "auto" means no effort was pinned (the CLI used the model default), so
        // don't surface it as a concrete effort level in the header.
        if !effort.isEmpty, effort != "auto" {
            label = "\(label) (effort: \(effort))"
        }
        return label
    }

    /// Local-time ISO-8601 timestamp with seconds precision and UTC offset.
    public static func processedAtNow(_ date: Date = Date()) -> String {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = .current
        formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssXXXXX"
        return formatter.string(from: date)
    }

    /// `{{KEY}}` substitution used for prompt templates.
    public static func renderTemplate(_ templateText: String, values: [String: String]) -> String {
        var rendered = templateText
        for (key, value) in values {
            rendered = rendered.replacingOccurrences(of: "{{\(key)}}", with: value)
        }
        return rendered
    }

    /// A light "made with TubeFold" credit appended to every saved `.md`.
    ///
    /// Telegraph does *not* inherit this — the article builder strips it (via
    /// `stripTubeFoldFooter`) and renders its own richer credit.
    public static func footerMarkdown() -> String {
        "\n---\n\n_Generated with [\(projectName)](\(projectURL))_\n"
    }

    // Matches the trailing block produced by `footerMarkdown` — an optional
    // rule then an italic "Generated with [label](href)" credit line at the
    // very end of the document. Label/href are matched generically so
    // re-branding the credit doesn't break the stripper.
    nonisolated(unsafe) private static let footerStripRegex =
        /\n*-{3,}[ \t]*\n+_Generated with \[[^\]]+\]\([^)]+\)_[ \t]*\n*$/

    /// Remove a trailing TubeFold credit footer, if present (no-op otherwise).
    public static func stripTubeFoldFooter(_ markdown: String) -> String {
        if let match = markdown.firstMatch(of: footerStripRegex),
           match.range.upperBound == markdown.endIndex {
            return String(markdown[..<match.range.lowerBound])
        }
        return markdown
    }

    nonisolated(unsafe) private static let outerFenceRegex =
        /```(?:markdown|md)?[ \t]*\n(?<body>.*)\n```[ \t]*/
            .dotMatchesNewlines()
            .ignoresCase()

    /// Unwrap a summary that the model wrapped in one outer ```markdown fence.
    public static func stripOuterMarkdownFence(_ text: String) -> String {
        let stripped = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if let match = stripped.wholeMatch(of: outerFenceRegex) {
            return String(match.output.body).trimmingCharacters(in: .whitespacesAndNewlines) + "\n"
        }
        return stripped + "\n"
    }

    /// Reject empty / degenerate provider output before it is saved.
    public static func validateProviderResponse(_ text: String) throws {
        let stripped = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if stripped.isEmpty {
            throw TubeFoldError.emptyProviderOutput
        }
        if stripped.count < 20 {
            throw TubeFoldError.providerOutputTooShort
        }
    }

    /// `H:MM:SS` / `M:SS` label for a duration in seconds; empty when unknown
    /// or negative.
    public static func durationHMS(_ seconds: Int?) -> String {
        guard let total = seconds, total >= 0 else { return "" }
        let hours = total / 3600
        let minutes = (total % 3600) / 60
        let secs = total % 60
        if hours > 0 {
            return String(format: "%d:%02d:%02d", hours, minutes, secs)
        }
        return String(format: "%d:%02d", minutes, secs)
    }
}

/// JSON-encode a string for the front matter: quoted, backslash/quote/control
/// characters escaped, non-ASCII kept verbatim.
func jsonEncodedString(_ value: String) -> String {
    var out = "\""
    for scalar in value.unicodeScalars {
        switch scalar {
        case "\"": out += "\\\""
        case "\\": out += "\\\\"
        case "\n": out += "\\n"
        case "\r": out += "\\r"
        case "\t": out += "\\t"
        case "\u{08}": out += "\\b"
        case "\u{0C}": out += "\\f"
        default:
            if scalar.value < 0x20 {
                out += String(format: "\\u%04x", scalar.value)
            } else {
                out.unicodeScalars.append(scalar)
            }
        }
    }
    return out + "\""
}
