import Foundation

/// Settings for one summary run.
public struct ProviderRunSettings: Sendable, Equatable {
    public let model: String
    /// "auto" (and "") mean "don't pin an effort" — the CLI uses the model's
    /// own default effort level.
    public let reasoningEffort: String
    public let timeout: TimeInterval

    public init(model: String = "", reasoningEffort: String = "auto", timeout: TimeInterval = 900) {
        self.model = model
        self.reasoningEffort = reasoningEffort
        self.timeout = timeout
    }
}

/// Outcome of a successful provider run: the Markdown body plus best-effort
/// token usage (the in-process replacement for the `.usage.json` sidecar).
public struct ProviderRunResult: Sendable, Equatable {
    public let markdownBody: String
    public let usage: ProviderUsage?

    public init(markdownBody: String, usage: ProviderUsage?) {
        self.markdownBody = markdownBody
        self.usage = usage
    }
}

public enum ProviderRunError: Error {
    case executableNotFound(String)
    case timedOut(seconds: Int)
    case processFailed(exitCode: Int32, detail: String, stderr: String)
    case emptyOutput

    public var userMessage: String {
        switch self {
        case let .executableNotFound(name): "Missing dependency: \(name)"
        case .timedOut: "Summary generation timed out."
        case .processFailed: "Could not generate summary."
        case .emptyOutput: "Summary output is empty."
        }
    }
}

/// A summary provider: turns a rendered prompt into the final Markdown body.
///
/// Key contract (unchanged from `providers/*.sh`): the provider produces
/// **only** the Markdown body — the YAML front matter is generated by the
/// pipeline, never by the model.
public protocol SummaryProvider: Sendable {
    var id: String { get }
    func generateSummary(prompt: String, settings: ProviderRunSettings) async throws -> ProviderRunResult
}

// MARK: - Codex

/// Direct `codex exec` invocation. Codex runs from an isolated temp cwd with `--sandbox read-only --ephemeral
/// --ignore-rules --skip-git-repo-check` so it can't touch repo or network
/// state; the prompt goes to stdin and the final message is captured via
/// `--output-last-message`.
public struct CodexProvider: SummaryProvider {
    public let id = "codex"
    public let executablePath: String

    public init(executablePath: String) {
        self.executablePath = executablePath
    }

    public func generateSummary(prompt: String, settings: ProviderRunSettings) async throws -> ProviderRunResult {
        guard FileManager.default.isExecutableFile(atPath: executablePath) else {
            throw ProviderRunError.executableNotFound("codex")
        }
        let workdir = try IsolatedWorkdir.make(prefix: "tubefold-codex-")
        defer { workdir.cleanUp() }
        let outputFile = workdir.url.appendingPathComponent("last-message.txt")

        var arguments = ["exec"]
        if !settings.model.isEmpty {
            arguments += ["--model", settings.model]
        }
        if !settings.reasoningEffort.isEmpty, settings.reasoningEffort != "auto" {
            arguments += ["-c", "model_reasoning_effort=\"\(settings.reasoningEffort)\""]
        }
        arguments += [
            "--sandbox", "read-only",
            "--cd", workdir.url.path,
            "--skip-git-repo-check",
            "--ephemeral",
            "--ignore-rules",
            "--color", "never",
            "--json",
            "--output-last-message", outputFile.path,
            "-",
        ]

        let result = try await Subprocess.run(
            executable: executablePath,
            arguments: arguments,
            currentDirectory: workdir.url,
            environment: Subprocess.controlledEnvironment(),
            stdin: prompt,
            timeout: settings.timeout
        )

        if result.timedOut {
            throw ProviderRunError.timedOut(seconds: Int(settings.timeout))
        }
        if result.exitCode != 0 {
            // Codex reports the real failure (e.g. an API 400) as an
            // "error"/"turn.failed" event on the --json stdout stream, NOT on
            // stderr — surface it so the cause isn't lost.
            let streamError = Self.errorFromJSONStream(result.stdout)
            let detail = ProviderFailure.classifyCodex(streamError.isEmpty ? result.stdout + "\n" + result.stderr : streamError)
            throw ProviderRunError.processFailed(
                exitCode: result.exitCode,
                detail: detail,
                stderr: [streamError, result.stderr.trimmingCharacters(in: .whitespacesAndNewlines)]
                    .filter { !$0.isEmpty }
                    .joined(separator: "\n")
            )
        }

        guard let body = try? String(contentsOf: outputFile, encoding: .utf8),
              !body.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw ProviderRunError.emptyOutput
        }
        return ProviderRunResult(markdownBody: body, usage: UsageParsing.codexUsage(fromJSONL: result.stdout))
    }

    /// Pull the human-readable message out of Codex's --json error events.
    /// Returns the last such message found, or `""` if none.
    static func errorFromJSONStream(_ stdout: String) -> String {
        var found = ""
        for rawLine in stdout.split(separator: "\n", omittingEmptySubsequences: true) {
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            guard !line.isEmpty,
                  let parsed = try? JSONSerialization.jsonObject(with: Data(line.utf8)),
                  let event = parsed as? [String: Any],
                  let type = event["type"] as? String,
                  type == "error" || type == "turn.failed" else {
                continue
            }
            var message = event["message"] as? String
            if message == nil, let error = event["error"] as? [String: Any] {
                message = error["message"] as? String
            }
            if let message, !message.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                found = message.trimmingCharacters(in: .whitespacesAndNewlines)
            }
        }
        return found
    }
}

// MARK: - Claude

/// Direct `claude --print` invocation. Runs from an isolated temp cwd (so the CLI never discovers a CLAUDE.md),
/// reads the prompt from stdin, and parses the model's text out of the JSON
/// result object on stdout. Uses the user's Claude subscription
/// (OAuth/keychain), not an API key.
public struct ClaudeProvider: SummaryProvider {
    public let id = "claude"
    public let executablePath: String

    public init(executablePath: String) {
        self.executablePath = executablePath
    }

    public func generateSummary(prompt: String, settings: ProviderRunSettings) async throws -> ProviderRunResult {
        guard FileManager.default.isExecutableFile(atPath: executablePath) else {
            throw ProviderRunError.executableNotFound("claude")
        }
        let workdir = try IsolatedWorkdir.make(prefix: "tubefold-claude-")
        defer { workdir.cleanUp() }

        var arguments = ["--print"]
        if !settings.model.isEmpty {
            arguments += ["--model", settings.model]
        }
        if !settings.reasoningEffort.isEmpty, settings.reasoningEffort != "auto" {
            arguments += ["--effort", settings.reasoningEffort]
        }
        arguments += ["--output-format", "json"]

        let result = try await Subprocess.run(
            executable: executablePath,
            arguments: arguments,
            currentDirectory: workdir.url,
            environment: Subprocess.controlledEnvironment(),
            stdin: prompt,
            timeout: settings.timeout
        )

        if result.timedOut {
            throw ProviderRunError.timedOut(seconds: Int(settings.timeout))
        }
        if result.exitCode != 0 {
            throw ProviderRunError.processFailed(
                exitCode: result.exitCode,
                detail: ProviderFailure.classifyClaude(result.stdout + "\n" + result.stderr),
                stderr: result.stderr.trimmingCharacters(in: .whitespacesAndNewlines)
            )
        }

        let (body, usage) = Self.parseResponse(result.stdout)
        guard !body.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw ProviderRunError.emptyOutput
        }
        return ProviderRunResult(markdownBody: body, usage: usage)
    }

    /// Pull the Markdown body and token usage out of the JSON result object.
    ///
    /// Falls back to treating stdout as the raw body (and skipping usage) if
    /// it is not the expected `--output-format json` object, so a CLI format
    /// change can never break summary generation.
    static func parseResponse(_ stdout: String) -> (body: String, usage: ProviderUsage?) {
        guard let parsed = try? JSONSerialization.jsonObject(with: Data(stdout.utf8)),
              let resultObject = parsed as? [String: Any],
              let body = resultObject["result"] as? String else {
            return (stdout, nil)
        }
        return (body, UsageParsing.claudeUsage(fromResultObject: resultObject))
    }
}

// MARK: - Script escape hatch + fake

/// Escape hatch for custom providers: any executable honoring the classic
/// `provider <prompt_file> <output_file>` contract keeps working.
public struct ScriptProvider: SummaryProvider {
    public let id: String
    public let scriptURL: URL
    public let environment: [String: String]

    public init(id: String, scriptURL: URL, environment: [String: String] = [:]) {
        self.id = id
        self.scriptURL = scriptURL
        self.environment = environment
    }

    public func generateSummary(prompt: String, settings: ProviderRunSettings) async throws -> ProviderRunResult {
        guard FileManager.default.isExecutableFile(atPath: scriptURL.path) else {
            throw ProviderRunError.executableNotFound(scriptURL.lastPathComponent)
        }
        let workdir = try IsolatedWorkdir.make(prefix: "tubefold-provider-\(id)-")
        defer { workdir.cleanUp() }
        let promptFile = workdir.url.appendingPathComponent("prompt.md")
        let outputFile = workdir.url.appendingPathComponent("output.md")
        try prompt.write(to: promptFile, atomically: true, encoding: .utf8)

        let result = try await Subprocess.run(
            executable: scriptURL.path,
            arguments: [promptFile.path, outputFile.path],
            currentDirectory: workdir.url,
            environment: Subprocess.controlledEnvironment(extra: environment),
            timeout: settings.timeout
        )
        if result.timedOut {
            throw ProviderRunError.timedOut(seconds: Int(settings.timeout))
        }
        if result.exitCode != 0 {
            throw ProviderRunError.processFailed(
                exitCode: result.exitCode,
                detail: "see provider output",
                stderr: result.stderr.trimmingCharacters(in: .whitespacesAndNewlines)
            )
        }
        guard let body = try? String(contentsOf: outputFile, encoding: .utf8),
              !body.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw ProviderRunError.emptyOutput
        }
        return ProviderRunResult(markdownBody: body, usage: nil)
    }
}

/// Swift test double replacing `providers/fake.sh`: canned Markdown, no
/// external process, no usage.
public struct FakeProvider: SummaryProvider {
    public let id = "fake"
    public let output: String

    public init(output: String = FakeProvider.defaultOutput) {
        self.output = output
    }

    public static let defaultOutput = """
    # Fake Summary

    - This summary was produced by the fake provider.
    - It exists so the pipeline can be exercised without a real model call.

    ## Details

    Nothing to see here; move along.
    """

    public func generateSummary(prompt _: String, settings _: ProviderRunSettings) async throws -> ProviderRunResult {
        ProviderRunResult(markdownBody: output, usage: nil)
    }
}

// MARK: - Helpers

enum ProviderFailure {
    static func classifyCodex(_ output: String) -> String {
        let text = output.lowercased()
        if text.contains("auth") || text.contains("login") || text.contains("not logged in") {
            return "authorization/login problem"
        }
        if text.contains("rate limit") || text.contains("quota") || text.contains("limit") {
            return "rate limit or quota problem"
        }
        if text.contains("network") || text.contains("connection") || text.contains("timed out") {
            return "network problem"
        }
        if text.contains("invalid_request_error") || text.contains("cannot be used with reasoning") {
            return "invalid request (model/reasoning-effort/tools combination)"
        }
        return "see Codex output below"
    }

    static func classifyClaude(_ output: String) -> String {
        let text = output.lowercased()
        if text.contains("not logged in") || text.contains("auth") || text.contains("login") {
            return "authorization/login problem"
        }
        if text.contains("rate limit") || text.contains("usage limit") || text.contains("quota") || text.contains("limit") {
            return "rate limit or quota problem"
        }
        if text.contains("network") || text.contains("connection") || text.contains("timed out") {
            return "network problem"
        }
        return "see Claude stderr"
    }
}

/// Fresh temp working directory for one provider run, removed afterwards.
struct IsolatedWorkdir {
    let url: URL

    static func make(prefix: String) throws -> IsolatedWorkdir {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent(prefix + UUID().uuidString)
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return IsolatedWorkdir(url: url)
    }

    func cleanUp() {
        try? FileManager.default.removeItem(at: url)
    }
}
